### ISSUE TITLE
[mac-chrome-게시글업로드] 게시글 삭제 후 작성 시 게시글 id 꼬이는 현상

### ISSUE THREAD

**Issue by hyoon1129** [100-hours-a-week/2-yuni-jeong-community-be#15]
**버그 설명**
게시글 id가 (게시글 길이 + 1)로 생성되어 작성된 게시글을 지우고 새로운 게시글 작성 시 게시글 데이터가 꼬임

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글이 3개 있는 상태(각각 post_id: 1, 2, 3) 에서 게시글 id가 2인 게시글 삭제
2. 새로운 게시글 작성(post_id가 3으로 생성됨)
3. 기존 게시글과 새로운 게시글 id가 같아서 새로운 게시글은 보이지 않고 기존의 3번 게시글이 2개 보임

**예상한 동작**
예상했던 일에 대한 명확하고 간결한 설명해주세요.
새로운 게시글이 정상적으로 조회되어야 함

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
![image](https://github.com/user-attachments/assets/6db0762d-2c56-459c-b11e-fbeb4abe0210)
post_id가 고유하지 못하게 생성됨

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: iOS
 - Browser: chrome

**Comment by ej31** [comment]
작년에 본 기사를 공유해드릴까 합니다.
[리소스의 ID, GUID로 할까 Sequential로 할까?](https://twitter.com/dylayed/status/1496020581610778625)

이슈 해결을 위해 UUID 를 사용하신것이 지금 시점에서는 괜찮으나 실제 세계에서는 어떻게 쓰여지는지 꼭 알아두어야합니다.
내가 알고 있는 지식이 어떤 트레이드 오프가 있는지 항상 감을 잡기 위해 안테나를 세워 두셔야 합니다! 👴

**Comment by ej31** [comment]
추가자료
- [TIL: 8 versions of UUID and when to use them](https://ntietz.com/blog/til-uses-for-the-different-uuid-versions/)
- [RDB UUID vs Integer](https://www.google.com/search?q=rdb+uuid+vs+integer)

**Comment by hyoon1129** [comment]
단순히 id 이슈가 생겨서 고유한 UUID로 해야지~ 하고 적용했는데 생각보다 rdb에서 pk를 뭘로 할 지 고려해야할 게 엄청 많았네요... GUID도 처음 들어봤어요! 정보 감사합니다 공부해보겠습니다
